plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.textrecognizer'
version = '0.1.0'

android {
  namespace "expo.modules.textrecognizer"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  // Reconocimiento de texto en el dispositivo (solo alfabeto latino, modelo incluido: funciona sin conexión)
  implementation 'com.google.mlkit:text-recognition:16.0.1'
}
